build: cairo: Fix static link error
By default, if you link static libraries (FLTK, DPF plugin) to Cairo,
linker will report a bunch of error of "undefined reference to
__imp_cairo*". It only happens on Win32.

This is because Cairo does not encourage static linkage on Win32
platform. To explicitly enable Win32 static build, we need to define
macro CAIRO_WIN32_STATIC_BUILD, globally.